#!/usr/bin/env bash

i=1
while [[ $i -le 7 ]]; do
echo "Days"
((i+=1))
done

i=8
if [[ $i -eq 8 ]]; then
echo "Week"

fi
((i+=1))

i=9
while [[ $i -gt 8 && $i -le 10 ]]; do
echo "Month"
((i+=1))
done
