#!/usr/bin/env bash
#manage

PID_FILE="/var/run/my_process.pid"

if [[ "$#" == "1" ]]; then
    case "$1" in
        start)
            if [[ -f "$PID_FILE" ]]; then
                echo "Process is already running."
                exit 1
            fi
            ./manage_my_process &
            echo "$!" > "$PID_FILE"
            echo "manage_my_process started"
            ;;
        stop)
            if [[ -f "$PID_FILE" ]]; then
                kill "$(cat "$PID_FILE")" 2>/dev/null
                rm "$PID_FILE"
                echo "manage_my_process stopped"
            else
                echo "No PID file found. Process might not be running."
            fi
            ;;
        restart)
            if [[ -f "$PID_FILE" ]]; then
                kill "$(cat "$PID_FILE")" 2>/dev/null
                rm "$PID_FILE"
                echo "manage_my_process stopped"
            fi
            ./manage_my_process &
            echo "$!" > "$PID_FILE"
            echo "manage_my_process restarted"
            ;;
        *)
            echo "Usage: manage_my_process {start|stop|restart}"
            ;;
    esac
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi

